services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  odoo:
    image: odoo:18.0
    depends_on:
      - db
    command: bash -lc "odoo -c /etc/odoo/odoo.conf -d ${DB_NAME:-Asai} -u asai_arm --stop-after-init --test-enable && exec odoo -c /etc/odoo/odoo.conf -d ${DB_NAME:-Asai}"
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
volumes:
  db-data:
  odoo-data: